CREATE TABLE IF NOT EXISTS Players (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TeamId INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Type INTEGER NOT NULL, -- 0: Hitter, 1: Pitcher
    -- Attributes
    Stamina INTEGER DEFAULT 0,
    Control INTEGER DEFAULT 0,
    Movement INTEGER DEFAULT 0,
    Velocity INTEGER DEFAULT 0,
    Contract INTEGER DEFAULT 0,
    Power INTEGER DEFAULT 0,
    Discipline INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS GameRecords (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    HomeScore INTEGER NOT NULL,
    AwayScore INTEGER NOT NULL,
    Winner TEXT NOT NULL,
    PlayedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GameLogs (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    GameId INTEGER NOT NULL,
    LogMessage TEXT NOT NULL,
    FOREIGN KEY(GameId) REFERENCES GameRecords(Id)
);
